### ISSUE TITLE
CI-message can contain multiple data in job_names field

### ISSUE THREAD

**Issue by Jurisak** [release-engineering/resultsdb-updater#25]
Testcases are now created from job_names field but it expects that there will be only single value.
This expectation is wrong because job_names can contain multiple values divided by comma. 

Therefore creation of testcases should be fixed.

**Comment by Jurisak** [comment]
Mentioned in pull request #22

**Comment by ralphbean** [comment]
@Jurisak when I reviewed the CI metrics doc in confluence, I got the impression that `job_names`, while plural, wasn't going to be a comma-separated list -- that it would only contain a single value.  I think there's a thread in the comments about it.  Can you confirm with Jiri Canderle that it can contain comma separated values before we act on this?

**Comment by Jurisak** [comment]
@ralphbean I have asked jcanderle and from what I heard the original intention was to have singular job_name value. But 'someone' needs it in plural. I will push more jcanderle to ensure it. Sorry for the delay.

**Comment by Jurisak** [comment]
@ralphbean After small discussion we decided that no one wants to use `job_names` as plural. Therefore it'll be singular and `job_names` is renamed to `job_name`. I'll create a pull request for this change.
