### ISSUE TITLE
Cannot use bulk interface with multiple results of the same test case

### ISSUE THREAD

**Issue by amisstea** [release-engineering/resultsdb-updater#29]
Resultsdb-updater assigns test case names using the property names of the `results` object when using the bulk message interface. This is a problem when trying to import multiple results for the same test case. It might make sense to convert the `results` object into an array and/or read the `testcase` property of each result instead. The single result import case uses the value of the `testcase` property so it would make sense to conform to that at the very least.

A workaround right now is to ensure uniqueness for the `results` property names but this is probably not how test case naming was intended to be used. Here is an example of this workaround:

```json
{
  "ref_url": "test_url", 
  "results": {
    "dva.ami.ami-1eebc979.ap-northeast-1.testcase_01_bash_history": {
      "data": {
        "item": "ami-1eebc979"
      }, 
      "note": null, 
      "outcome": "PASSED", 
      "ref_url": "test_url", 
      "testcase": "ami.dva.testcase_01_bash_history"
    }, 
    "dva.ami.ami-57d7b041.us-east-1.testcase_01_bash_history": {
      "data": {
        "item": "ami-57d7b041"
      }, 
      "note": null, 
      "outcome": "PASSED", 
      "ref_url": "test_url", 
      "testcase": "ami.dva.testcase_01_bash_history"
    } 
}
```

**Comment by ralphbean** [comment]
@amisstea we're game to fix this, but want to understand how urgent it is for you so we can schedule it.

Is your workaround sufficient for now?

**Comment by amisstea** [comment]
@ralphbean, it's not urgent and I can make do with the workaround.

**Comment by ralphbean** [comment]
OK.  We've got it in our JIRA backlog for now.

**Comment by ralphbean** [comment]
Ran into this in grooming today: I don't think we're going to get to this anytime soon.

Closing this as "wontfix".  If it is important, please re-raise it with us and we'll take another look.
