### ISSUE TITLE
Add UMB support

### ISSUE THREAD

**Issue by thrix** [release-engineering/resultsdb-updater#32]
As we are moving to UMB as the message brooker, resultsdb needs to be able to consume messages also from it.

**Comment by ralphbean** [comment]
True, true.

For some time, we will likely need to run *two* resultsdb-updater instances.  One on the UMB and one on the CI bus.

Do you know how soon you want to be "fully" on the UMB?

**Comment by thrix** [comment]
Unfortunately now, it should have been already shutdown, the information is a bit unclear :(

**Comment by thrix** [comment]
A lot of teams are still using it, so I do not think it will shutdown very soon, I will try to get an update

**Comment by thrix** [comment]
Added a link to Jira with some more information, but the date is unclear

**Comment by thrix** [comment]
Nah, reading to quickly. Well we should have been already, but I see a month a realistic time when it would be nice to be there.
