### ISSUE TITLE
Set up travis CI on the master branch

### ISSUE THREAD

**Issue by csomh** [release-engineering/resultsdb-updater#58]
[It seems](https://travis-ci.org/release-engineering/resultsdb-updater/branches) that merges to master are not picked up by travis. Probably 'Build pushed branches' has to be turned on.

README could be updated to include the build badge for the master branch after doing the above.

**Comment by mprahl** [comment]
Turned it on. Try now?

**Comment by csomh** [comment]
Let's check if a build will be triggered when #56 is merged.

**Comment by csomh** [comment]
Cool! [It's working](https://travis-ci.org/release-engineering/resultsdb-updater/branches) now.
